import json
import pytest
import numpy as np
import lightgbm as lgb
from pathlib import Path

def test_golden_inference_equivalence():
    """
    Ensures the lightweight frozen-scorer.txt produces EXACTLY the same predictions
    as the golden predictions generated by the original full ML stack.
    """
    model_dir = Path("dashboard/model")
    
    # Load lightweight model
    scorer_path = model_dir / "frozen-scorer.txt"
    bst = lgb.Booster(model_file=str(scorer_path))
    
    # Load golden inference set
    golden_path = model_dir / "golden_predictions.json"
    with open(golden_path, "r") as f:
        golden_data = json.load(f)
        
    X_test = np.array(golden_data["features"])
    expected_preds = np.array(golden_data["predictions"])
    
    # Run lightweight inference
    actual_preds = bst.predict(X_test)
    
    # Gate A - Equivalence Tolerance
    max_error = np.max(np.abs(actual_preds - expected_preds))
    print(f"Max Absolute Error: {max_error}")
    assert max_error < 1e-10, "FAIL: Lightweight scorer deviates from original model."
    
    # Gate A - Classification Agreement
    threshold_path = model_dir / "threshold.json"
    with open(threshold_path, "r") as f:
        threshold = json.load(f)["threshold"]
        
    expected_classes = (expected_preds >= threshold).astype(int)
    actual_classes = (actual_preds >= threshold).astype(int)
    
    classification_match = np.mean(expected_classes == actual_classes)
    assert classification_match == 1.0, f"FAIL: Classification agreement is {classification_match * 100}% (Must be 100%)"

if __name__ == "__main__":
    pytest.main([__file__])
