import json
import pytest
import numpy as np
from pathlib import Path
import sys
import os

# Add dashboard/api/ to path so we can import predict.py directly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "api"))
import predict

FEATURE_ORDER = [
    "past_launches",
    "past_buys",
    "past_sells",
    "past_burns",
    "deployer_age_seconds"
]

def test_feature_order_matches_manifest():
    """
    Ensures the feature order in the dashboard scorer matches the frozen manifest.
    A perfectly correct model with incorrectly ordered inputs produces wrong results.
    """
    schema_path = Path(__file__).resolve().parent.parent.parent / "model" / "feature_schema.json"
    with open(schema_path) as f:
        schema = json.load(f)
    assert schema["features"] == FEATURE_ORDER, \
        f"Feature order mismatch!\nSchema: {schema['features']}\nExpected: {FEATURE_ORDER}"

def test_golden_inference_equivalence():
    """
    Ensures the pure Python AST scorer (predict.py) produces EXACTLY the same
    predictions as the golden predictions generated by the original LightGBM stack.
    Max absolute error must be < 1e-6. Classification agreement must be 100%.
    """
    model_dir = Path(__file__).resolve().parent.parent.parent / "model"
    
    golden_path = model_dir / "golden_predictions.json"
    with open(golden_path) as f:
        golden_data = json.load(f)
        
    X_test = golden_data["features"]
    expected_preds = np.array(golden_data["predictions"])
    
    # Run AST inference — m2cgen returns [P(class_0), P(class_1)]
    actual_preds = np.array([predict.score(x)[1] for x in X_test])
    
    # Gate A: Numerical Equivalence
    max_error = np.max(np.abs(actual_preds - expected_preds))
    print(f"Max Absolute Error: {max_error:.2e}")
    assert max_error < 1e-6, f"FAIL: AST scorer deviates from golden model. Max error: {max_error:.2e}"
    
    # Gate B: Classification Agreement
    threshold_path = model_dir / "threshold.json"
    with open(threshold_path) as f:
        threshold = json.load(f)["threshold"]
        
    expected_classes = (expected_preds >= threshold).astype(int)
    actual_classes = (actual_preds >= threshold).astype(int)
    
    classification_match = np.mean(expected_classes == actual_classes)
    assert classification_match == 1.0, \
        f"FAIL: Classification agreement is {classification_match * 100:.2f}% (required 100%)"
    print("Golden Inference Contract: PASS — 100% equivalence verified")

def test_unknown_label_protection():
    """
    Verifies the canonical counts from the experiment manifest.
    Unknown labels must never have been silently converted to negatives.
    """
    manifest_path = Path(__file__).resolve().parent.parent.parent.parent / "submission" / "results" / "experiment_manifest.json"
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
        ds = manifest["dataset"]
        assert ds["mapped_positive_labels"] == 13818
        assert ds["unknown_positive_labels"] == 2109
        total_target = ds["mapped_positive_labels"] + ds["unknown_positive_labels"]
        assert total_target == 15927, f"Label accounting mismatch: {total_target} != 15927"
        assert "EXCLUDED" in ds["unknown_treatment"].upper(), \
            "Unknowns must be EXCLUDED, not converted to negatives"
    else:
        pytest.skip("experiment_manifest.json not found at expected path")

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
