import json
import pytest
import numpy as np
import math
from pathlib import Path
import sys

# Add api/ to path to import pure_scorer
sys.path.append(str(Path("dashboard/api").resolve()))
from pure_scorer import score

def test_golden_inference_equivalence():
    """
    Ensures the pure Python scorer produces EXACTLY the same predictions
    as the golden predictions generated by the original full ML stack.
    """
    model_dir = Path("dashboard/model")
    
    # Load golden inference set
    golden_path = model_dir / "golden_predictions.json"
    with open(golden_path, "r") as f:
        golden_data = json.load(f)
        
    X_test = golden_data["features"]
    expected_preds = np.array(golden_data["predictions"])
    
    # Run pure python inference (LGBMClassifier m2cgen returns [P(class_0), P(class_1)])
    actual_preds = np.array([score(x)[1] for x in X_test])
    
    # Gate A - Equivalence Tolerance
    max_error = np.max(np.abs(actual_preds - expected_preds))
    print(f"Max Absolute Error: {max_error}")
    assert max_error < 1e-6, f"FAIL: Pure Python scorer deviates from original model. Max error: {max_error}"
    
    # Gate A - Classification Agreement
    threshold_path = model_dir / "threshold.json"
    with open(threshold_path, "r") as f:
        threshold = json.load(f)["threshold"]
        
    expected_classes = (expected_preds >= threshold).astype(int)
    actual_classes = (actual_preds >= threshold).astype(int)
    
    classification_match = np.mean(expected_classes == actual_classes)
    assert classification_match == 1.0, f"FAIL: Classification agreement is {classification_match * 100}% (Must be 100%)"

if __name__ == "__main__":
    pytest.main([__file__])
