from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import json
import math
from pathlib import Path

# Import the pure Python scorer generated by m2cgen!
from pure_scorer import score

app = FastAPI(title="Zero-Block Deconstruction Inference API")

# Load threshold at startup
MODEL_DIR = Path(__file__).resolve().parent.parent / "model"
THRESHOLD_PATH = MODEL_DIR / "threshold.json"

try:
    with open(THRESHOLD_PATH, "r") as f:
        threshold_data = json.load(f)
        FROZEN_THRESHOLD = threshold_data["threshold"]
except Exception as e:
    FROZEN_THRESHOLD = 0.5
    print(f"Error loading threshold: {e}")

class FeatureVector(BaseModel):
    past_launches: float
    past_buys: float
    past_sells: float
    past_burns: float
    deployer_age_seconds: float

@app.post("/api/predict")
async def predict(features: FeatureVector):
    X_input = [
        features.past_launches,
        features.past_buys,
        features.past_sells,
        features.past_burns,
        features.deployer_age_seconds
    ]
    
    # Run inference using the pure Python AST
    raw_score = score(X_input)
    
    # m2cgen for LGBMClassifier binary classification returns [P(class_0), P(class_1)]
    prob = float(raw_score[1])
    
    return {
        "probability": prob,
        "top_5_percent": prob >= FROZEN_THRESHOLD,
        "model_version": "v1.0.0-final",
        "policy_version": "top_5_percent"
    }
